language: python
python:
  - "2.7"
install:
  - "pip install -r newsParser/requirements.txt"
  - "pip install python-coveralls"
  - "pip install coverage"
script: 
  - nosetests --with-coverage --cover-package=.
notifications:
  slack: lab3l7:Lx3Dd2gLGNZGqLo7Ki4kklYN
after_success:  
  - coveralls
